version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: dairy
      POSTGRES_USER: dairy_app
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - ./Scripts/postgres:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dairy.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  web:
    build: ./src/Web
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
